### ISSUE TITLE
TP 3 Draft Specs

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#225]
This issue is a central hub for the specifications of TP 3. It can refer to more detailed issues but should offer a summary of the features we plan for the next major release of TP.

### Releasable singletons

We should release all internal providers under memory pressure, but not automatically as some can't recover their state. Thus, users should have full control over this. We should provide different mechanisms to let user mark classes whose singletons can be released:

* add an annotation @Releasable that can apply to a type that is injected
* add .markAsReleasable() to the bindings API

Details in #212 

### Better scope annotations

For now, only "singleton classes" can be annotated to indicate in which scope TP should create an instance of theses classes. We want to extend this mechanism, which actually breaks the JSR 330, and allows things like:

```java
@ActivityScope 
public class Foo {}
```
Which means Foo can only be created by TP inside a scope that supports the `@ActivityScope`, but without `Foo` being a singleton. A singleton would be expressed by:

```java
@ActivityScope  @Singleton
public class FooSingleton {}
```

Note that this new notation is just making more clear and distinct to which scope entities belong and how they are recycled. These 2 concepts are currently entangled in JSR 330. Also, using the new annotation model will still preserve the strong contract of  

```java
@Singleton
public class FooSingleton {}
```
being a singleton of the root scope, as everyone would expect.

This change ***should*** not require any binding API changes.

### Better TP API

Changing the API will also help users to be sure of which TP version they are using and avoid misinterpreting the new annotation model.

* [x] `Toothpick.inject(foo, scope)` --> `scope.inject(foo)`, more details in #217.
* [x] give scopes a fluent API, more details in #218.
* [x] change bind --> support for scope annotation, more details in #169 
* [x] allow to inject package-protected classes, right now we only allow public #227 (testEmptyConstructor_shouldWork_whenConstructorIsProtected)
* [x] allow @Inject annotated methods to send Exceptions, more details in #200 
* [x] ~give a base class to factories and MemberInjectors? to limit the generated code size~ (#347).

### Improve Examples

* [x] Fix Test examples by using ToothpickRule
* [x] Add a @Singleton example
* [x] Add Presenter and Flow example (state preservation)
* [x] Improve coding style in examples -> inner classes, bad names, ...
* [x] Make sure all examples work (https://github.com/stephanenicolas/toothpick/issues/337)

### KTP

https://github.com/stephanenicolas/toothpick/issues/316

### Documentation

* [x] Improve documentation and come with a way to represent the way it works internally for maintainers.

### Misc

* [x] Add test to make sure that releasable is working
* [x] Add test to verify that the new scope and singleton system works
* [x] Add tests to make sure that the whole library works for Kotlin
* [x] Add support for Mockk (https://github.com/stephanenicolas/toothpick/issues/334)
* [x] ~Being able to test scope graph at build time using unit tests~ (#348)
* [x] switch to Mockito internally
* [x] make scopes lifecycle-aware (https://github.com/stephanenicolas/toothpick/issues/332)

### other ideas

Add an annotation `@ShouldBeLazy` so that a class can only be injected lazily. This could help for instance to delay the creation of some network related classes..

**Comment by ultimate-deej** [comment]
Let me share my thoughts on it.
1. Releasable singletons. **tldr**: I doubt this is something a DI library should do.
I'm strongly against this. This will introduce more complexity with little to no benefits. If user needs to handle low memory conditions they should do it solely on their own without resorting to a DI library. After all, Toothpick is a dependency injection library, not a memory management library. Finally, this will make singletons not so singletons.
2. Better scope annotations. Love it! Will definitely give more control and make things clearer. As for JSR 330, I don't think it will break the [standard](https://javax-inject.github.io/javax-inject/api/javax/inject/Scope.html) (emphasis mine):
    > If a scope annotation is present, the injector **_may_** retain the instance for possible reuse in a later injection

    However, it might in fact cause confusion to users.
3. The rest looks 👍, except that it is unclear to me what #169 is about

**Comment by ultimate-deej** [comment]
1. Are you talking about the overhead created by TP, or just about the fact that long-living objects consume memory? If it is the former case, how significant is it? If it is the latter, again, the user is responsible and there is no need to aid him in this. You might also consider the dagger's team experience https://github.com/google/dagger/issues/1117, they have dropped a similar feature.
2. Yeah, didn't think of that. What if you leave `@Singleton` intact, thus keeping compliance to the standard, and instead create a custom annotation similar to `@ProvidesSingletonInScope`? Like `@SingletonInScope` for instance. This would clearly indicate that it's not standard as well as better communicate the intent (because of a little more verbosity).
3. Thx for the explanation!

**Comment by stephanenicolas** [comment]
1. No there is no significant overhead, I am talking about the ability to remove these long living objects. 
Unfortunately, users can't release them. TP 1/2 offers Singletons that can't be released, we will offer releasable ones as well. 
Thx for the dagger thread about the removal, I didn't know about that. The main reason they want to get rid of this is for decreasing complexity. Let's see what it gives in TP, but at Groupon,we have quite some use cases for this. I believe the implementation is simpler for TP.
2. We are really looking for something clear and intuitive, not sure yours is ;) Also, we will preserve the very essential contract of '@Singleton' annotated classes. What will change is how custom Scopes are used. 
3.

**Comment by L7ColWinters** [comment]
I really like the idea of releasable singletons with an annotation since our team wanted to increase the performance of tp by caching classes that had no state but these "singletons" could be cleaned out and recreated since we only made it singleton to speed up the injection. Basically lazy garbage collection.

**Comment by stephanenicolas** [comment]
TODO: better CHANGELOG, README, and wiki landing page. To be updated for TP3.

**Comment by stephanenicolas** [comment]
Ticket closed as all was released in 3.0.0
