### ISSUE TITLE
TODO before releasing 1.0.0-RC1

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#43]
Codewise : 

* [ ] increase test coverage to 99% + (currently 95%)
* [x] add cycle detection at runtime
* [x] add debug and prod mode ^
* [x] create GH readme
* [x] create useful wiki
* [x] prepare article for announcement
* [x] fix maven publishing
* [x] release to central 
* [x] ask for external reviews
